import chalk from 'chalk';
import { displayHelp } from '@sketchmine/node-helpers';
import { resolve } from 'path';

/**
 * Configuration arguments for the command line args
 */
export interface ConfigArguments {
  meta: string;
  appShell: string;
  examples: string; /** path to examples folder */
}

const helpText = `
This package is only meant for internal use @Dynatrace.
The app-builder builds the example angular application out of our
pure examples to generate the dynatrace components library.
`;

const cmdFlags = [
  {
    flags: ['h', 'help'],
    text: 'displays the help page 📓',
  },
  {
    flags: ['c', 'config'],
    text: chalk`path to the configuration file {grey (config.json)} ⚙️`,
  },
  {
    divider: true,
    text: 'if no config is provided those three arguments have to be provided:',
  },
  {
    flags: ['appShell'],
    text: 'path to the angular app shell',
  },
  {
    flags: ['meta'],
    text: chalk`path to the meta-information.json that was generated by the {grey @sketchmine/code-analyzer}`,
  },
  {
    flags: ['examples'],
    text: 'path to the pure examples.',
  },
];

const DEFAULT_CONFIG = 'config.json';

/**
 * Merges the default config arguments with the command line inputs
 * @param args Merged config arguments
 * @return {ConfigArguments}
 */
export function parseCommandlineArgs(args: string[]): ConfigArguments {
  const parsedArgs = require('minimist')(args);

  if (parsedArgs.hasOwnProperty('h') || parsedArgs.hasOwnProperty('help') || args.length === 0) {
    displayHelp(helpText, cmdFlags);
  }

  const defaultConfig = require(resolve(DEFAULT_CONFIG));
  let conf = {};

  if (parsedArgs.hasOwnProperty('c') || parsedArgs.hasOwnProperty('config')) {
    conf = require(resolve(parsedArgs.c || parsedArgs.config));
  }

  if (parsedArgs.hasOwnProperty('appShell')) { conf['appShell'] = parsedArgs.appShell; }
  if (parsedArgs.hasOwnProperty('meta')) { conf['meta'] = parsedArgs.meta; }
  if (parsedArgs.hasOwnProperty('examples')) { conf['examples'] = parsedArgs.examples; }

  return Object.assign(defaultConfig, conf);
}
